name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Lint JavaScript
        run: npm run lint

      - name: Lint Markdown
        run: npm run lint:md

      - name: Build project
        run: npm run build

      - name: Check links
        run: npm run check-links
